/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttentionTabs: typeof import('./src/components/AttentionTabs.vue')['default']
    EntityCard: typeof import('./src/components/EntityCard.vue')['default']
    LoadingSkeleton: typeof import('./src/components/LoadingSkeleton.vue')['default']
    PipelineChart: typeof import('./src/components/PipelineChart.vue')['default']
    QuickLinks: typeof import('./src/components/QuickLinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatPanel: typeof import('./src/components/StatPanel.vue')['default']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
  }
}
